In [1]:
import pandas as pd

In [23]:
#creating dataframe using list of lists

data=[["sai",100],["john",90],["johny",89]]
data

[['sai', 100], ['john', 90], ['johny', 89]]

In [24]:
pd.DataFrame(data,columns=["Name","Marks"])

    Name  Marks
0    sai    100
1   john     90
2  johny     89

In [25]:
#creating dataframe using dictionary

data={"a":[10,29,38],"b":[39,48,28]}

In [26]:
df=pd.DataFrame(data)
df

    a   b
0  10  39
1  29  48
2  38  28

In [22]:
#creating dataframe using numpy
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(arr,columns=["A","B","C"])
df

   A  B  C
0  1  2  3
1  4  5  6

In [33]:
#creting dataframe using xl files
df=pd.read_excel("data.xlsx")
df

      Name  Marks  School
0      Sai     56  smvitm
1     john     76      hj
2  johnson     78      kk
3      joe     59     klo
4     riya     56      hf
5   allice     87    dhhd
6      bob     84    bsdk

In [34]:
df=pd.read_csv("data.csv")
df

      Name  Marks  School
0      Sai     56  smvitm
1     john     76      hj
2  johnson     78      kk
3      joe     59     klo
4     riya     56      hf
5   allice     87    dhhd
6      bob     84    bsdk

In [35]:
#using json

df=pd.read_json("data.json")
df

    Name  Age
0    Sai   20
1  Harry   55

In [36]:
#create df from dataset links

df=pd.read_csv("https://gist.githubusercontent.com/Thanatoz-1/9e7fdfb8189f0cdf5d73a494e4a6392a/raw/aaecbd14aeaa468cd749528f291aa8a30c2ea09e/iris_dataset.csv")
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [38]:
#EDA--->exploratory data analysis

In [40]:
df.head()   #first five rows

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

In [41]:
df.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [43]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.054000,3.758667,1.198667
std,0.828066,0.433594,1.764420,0.763161
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [45]:
df.shape

(150, 5)

In [47]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')