In [1]:
import pandas as pd

In [5]:
dis=pd.read_csv("FIFA.csv")
dis

,Country,Total_Titles,Years_Won,Sample_Host,Rank
0,Brazil,5,"1958, 1962, 1970, 1994, 2002",South Korea / Japan,1
1,Italy,4,"1934, 1938, 1982, 2006",Germany,2
2,Argentina,3,"1978, 1986, 2022",Qatar,3
3,West Germany,3,"1954, 1974, 1990",Italy,4
4,France,2,"1998, 2018",Russia,5
5,Uruguay,2,"1930, 1950",Brazil,6
6,England,1,1966,England,7
7,Germany,1,2014,Brazil,8
8,Spain,1,2010,South Africa,9

In [8]:
dis['Country'][4]

'France'

In [10]:
type(dis['Country'])

pandas.core.series.Series

In [14]:
dis[['Country','Rank']]

        Country  Rank
0        Brazil     1
1         Italy     2
2     Argentina     3
3  West Germany     4
4        France     5
5       Uruguay     6
6       England     7
7       Germany     8
8         Spain     9

In [69]:
dis.loc[3]   #found by row label

Country             West Germany
Total_Titles                   3
Years_Won       1954, 1974, 1990
Sample_Host                Italy
Rank                           4
Name: 3, dtype: object

In [71]:
dis.loc[3,"Country"]="india"   #change the value 
dis

,Country,Total_Titles,Years_Won,Sample_Host,Rank
0,Brazil,5,"1958, 1962, 1970, 1994, 2002",South Korea / Japan,1
1,Italy,4,"1934, 1938, 1982, 2006",Germany,2
2,Argentina,3,"1978, 1986, 2022",Qatar,3
3,india,3,"1954, 1974, 1990",Italy,4
4,France,2,"1998, 2018",Russia,5
5,Uruguay,2,"1930, 1950",Brazil,6
6,England,1,1966,England,7
7,Germany,1,2014,Brazil,8
8,Spain,1,2010,South Africa,9

In [26]:
#particular row and column

dis.loc[6,'Years_Won']

'1966'

In [17]:
dis.iloc[3]   #by index

Country             West Germany
Total_Titles                   3
Years_Won       1954, 1974, 1990
Sample_Host                Italy
Rank                           4
Name: 3, dtype: object

In [36]:
dis.loc[0:3,['Country','Sample_Host']]

        Country          Sample_Host
0        Brazil  South Korea / Japan
1         Italy              Germany
2     Argentina                Qatar
3  West Germany                Italy

In [30]:
dis.iloc[3,2]   #[row,col]

'1954, 1974, 1990'

In [39]:
dis.iloc[0:3,[3,4]]   #3 is excluded

           Sample_Host  Rank
0  South Korea / Japan     1
1              Germany     2
2                Qatar     3

In [41]:
dis.at[0,"Country"]   #access 1 particular element

'Brazil'

In [47]:
dis.iat[0,0]

'Brazil'

In [48]:
#filtering

In [59]:
dis[dis["Total_Titles"]>3]    #dis[where dis[total_titles]>3

,Country,Total_Titles,Years_Won,Sample_Host,Rank
0,Brazil,5,"1958, 1962, 1970, 1994, 2002",South Korea / Japan,1
1,Italy,4,"1934, 1938, 1982, 2006",Germany,2

In [60]:
dis[dis["Total_Titles"]>3]['Country']

0    Brazil
1     Italy
Name: Country, dtype: object

In [64]:
dis[(dis["Total_Titles"]>3) & (dis["Rank"]>1)]

  Country  Total_Titles               Years_Won Sample_Host  Rank
1   Italy             4  1934, 1938, 1982, 2006     Germany     2

In [65]:
dis[(dis["Total_Titles"]>3) | (dis["Rank"]>1)]

,Country,Total_Titles,Years_Won,Sample_Host,Rank
0,Brazil,5,"1958, 1962, 1970, 1994, 2002",South Korea / Japan,1
1,Italy,4,"1934, 1938, 1982, 2006",Germany,2
2,Argentina,3,"1978, 1986, 2022",Qatar,3
3,West Germany,3,"1954, 1974, 1990",Italy,4
4,France,2,"1998, 2018",Russia,5
5,Uruguay,2,"1930, 1950",Brazil,6
6,England,1,1966,England,7
7,Germany,1,2014,Brazil,8
8,Spain,1,2010,South Africa,9

In [68]:
dis.query("Total_Titles > 2 or Rank >3")

,Country,Total_Titles,Years_Won,Sample_Host,Rank
0,Brazil,5,"1958, 1962, 1970, 1994, 2002",South Korea / Japan,1
1,Italy,4,"1934, 1938, 1982, 2006",Germany,2
2,Argentina,3,"1978, 1986, 2022",Qatar,3
3,West Germany,3,"1954, 1974, 1990",Italy,4
4,France,2,"1998, 2018",Russia,5
5,Uruguay,2,"1930, 1950",Brazil,6
6,England,1,1966,England,7
7,Germany,1,2014,Brazil,8
8,Spain,1,2010,South Africa,9