In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("movies.csv")
df

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,NaN,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
7664,Dream Round,NaN,Comedy,2020,"February 7, 2020 (United States)",4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0
7665,Saving Mbango,NaN,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN
7666,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0
7667,Tee em el,NaN,Horror,2020,"August 19, 2020 (United States)",5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,NaN,NaN,PK 65 Films,102.0

In [14]:
df2=df.drop(df[df["year"]>1980].index)
df2

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,The Gong Show Movie,R,Comedy,1980,"May 23, 1980 (United States)",4.3,740.0,Chuck Barris,Chuck Barris,Chuck Barris,United States,NaN,6621520.0,Chuck Barris Productions,89.0
88,Gilda Live,R,Comedy,1980,"March 28, 1980 (United States)",6.8,599.0,Mike Nichols,Anne Beatts,Gilda Radner,United States,NaN,2261507.0,Broadway Productions,96.0
89,Why Would I Lie?,PG,Comedy,1980,"August 8, 1980 (United States)",6.5,211.0,Larry Peerce,Hollis Hodges,Treat Williams,United States,NaN,1175855.0,Metro-Goldwyn-Mayer (MGM),105.0
90,First Family,R,Comedy,1980,"December 25, 1980 (United States)",4.3,593.0,Buck Henry,Buck Henry,Bob Newhart,United States,NaN,15198912.0,F.F. Associates,97.0
91,Mantis Fist Fighter,NaN,Action,1980,"July 9, 1982 (United States)",6.7,230.0,Wing-Cho Yip,Hsin-Yi Chang,Ka-Yan Leung,Hong Kong,NaN,NaN,East Asia Film Company,89.0

In [23]:
df3=df2.sort_values("score",ascending=False) #descending
df3

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
49,Lion of the Desert,PG,Biography,1980,"May 16, 1981 (Japan)",8.3,15000.0,Moustapha Akkad,David Butler,Anthony Quinn,Libya,35000000.0,NaN,Falcon International Productions,173.0
7,Raging Bull,R,Biography,1980,"December 19, 1980 (United States)",8.2,330000.0,Martin Scorsese,Jake LaMotta,Robert De Niro,United States,18000000.0,23402427.0,Chartoff-Winkler Productions,129.0
66,Moscow Does Not Believe in Tears,PG,Comedy,1980,"February 11, 1980 (Soviet Union)",8.1,12000.0,Vladimir Menshov,Valentin Chernykh,Vera Alentova,Soviet Union,900000.0,NaN,Mosfilm,150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,The Boogey Man,R,Horror,1980,"November 7, 1980 (United States)",4.6,3900.0,Ulli Lommel,Ulli Lommel,Suzanna Love,United States,300000.0,NaN,The Jerry Gross Organization,82.0
87,The Gong Show Movie,R,Comedy,1980,"May 23, 1980 (United States)",4.3,740.0,Chuck Barris,Chuck Barris,Chuck Barris,United States,NaN,6621520.0,Chuck Barris Productions,89.0
90,First Family,R,Comedy,1980,"December 25, 1980 (United States)",4.3,593.0,Buck Henry,Buck Henry,Bob Newhart,United States,NaN,15198912.0,F.F. Associates,97.0
52,Can't Stop the Music,PG,Biography,1980,"June 20, 1980 (United States)",4.2,3700.0,Nancy Walker,Bronte Woodard,Ray Simpson,United States,20000000.0,NaN,EMI Films,124.0
80,Phobia,R,Drama,1980,"September 9, 1980 (United States)",4.0,546.0,John Huston,Gary Sherman,Paul Michael Glaser,Canada,5100000.0,59167.0,Borough Park Productions,94.0

In [24]:
#df3.reset_index(drop="True")   #in the above cell index are mixed ,,it will resets the index form 0.... And it doesnot effect the df3
                    #cretes new col of index (to drop nwe index col drop=True )

In [19]:
df3

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
49,Lion of the Desert,PG,Biography,1980,"May 16, 1981 (Japan)",8.3,15000.0,Moustapha Akkad,David Butler,Anthony Quinn,Libya,35000000.0,NaN,Falcon International Productions,173.0
7,Raging Bull,R,Biography,1980,"December 19, 1980 (United States)",8.2,330000.0,Martin Scorsese,Jake LaMotta,Robert De Niro,United States,18000000.0,23402427.0,Chartoff-Winkler Productions,129.0
66,Moscow Does Not Believe in Tears,PG,Comedy,1980,"February 11, 1980 (Soviet Union)",8.1,12000.0,Vladimir Menshov,Valentin Chernykh,Vera Alentova,Soviet Union,900000.0,NaN,Mosfilm,150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,The Boogey Man,R,Horror,1980,"November 7, 1980 (United States)",4.6,3900.0,Ulli Lommel,Ulli Lommel,Suzanna Love,United States,300000.0,NaN,The Jerry Gross Organization,82.0
87,The Gong Show Movie,R,Comedy,1980,"May 23, 1980 (United States)",4.3,740.0,Chuck Barris,Chuck Barris,Chuck Barris,United States,NaN,6621520.0,Chuck Barris Productions,89.0
90,First Family,R,Comedy,1980,"December 25, 1980 (United States)",4.3,593.0,Buck Henry,Buck Henry,Bob Newhart,United States,NaN,15198912.0,F.F. Associates,97.0
52,Can't Stop the Music,PG,Biography,1980,"June 20, 1980 (United States)",4.2,3700.0,Nancy Walker,Bronte Woodard,Ray Simpson,United States,20000000.0,NaN,EMI Films,124.0
80,Phobia,R,Drama,1980,"September 9, 1980 (United States)",4.0,546.0,John Huston,Gary Sherman,Paul Michael Glaser,Canada,5100000.0,59167.0,Borough Park Productions,94.0

In [26]:
df3.sort_index()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,The Gong Show Movie,R,Comedy,1980,"May 23, 1980 (United States)",4.3,740.0,Chuck Barris,Chuck Barris,Chuck Barris,United States,NaN,6621520.0,Chuck Barris Productions,89.0
88,Gilda Live,R,Comedy,1980,"March 28, 1980 (United States)",6.8,599.0,Mike Nichols,Anne Beatts,Gilda Radner,United States,NaN,2261507.0,Broadway Productions,96.0
89,Why Would I Lie?,PG,Comedy,1980,"August 8, 1980 (United States)",6.5,211.0,Larry Peerce,Hollis Hodges,Treat Williams,United States,NaN,1175855.0,Metro-Goldwyn-Mayer (MGM),105.0
90,First Family,R,Comedy,1980,"December 25, 1980 (United States)",4.3,593.0,Buck Henry,Buck Henry,Bob Newhart,United States,NaN,15198912.0,F.F. Associates,97.0
91,Mantis Fist Fighter,NaN,Action,1980,"July 9, 1982 (United States)",6.7,230.0,Wing-Cho Yip,Hsin-Yi Chang,Ka-Yan Leung,Hong Kong,NaN,NaN,East Asia Film Company,89.0

In [12]:
df2.sort_values(["score","votes"])   #firstly it sort by score if columns of score are same then it sort by votes
df2

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,The Gong Show Movie,R,Comedy,1980,"May 23, 1980 (United States)",4.3,740.0,Chuck Barris,Chuck Barris,Chuck Barris,United States,NaN,6621520.0,Chuck Barris Productions,89.0
88,Gilda Live,R,Comedy,1980,"March 28, 1980 (United States)",6.8,599.0,Mike Nichols,Anne Beatts,Gilda Radner,United States,NaN,2261507.0,Broadway Productions,96.0
89,Why Would I Lie?,PG,Comedy,1980,"August 8, 1980 (United States)",6.5,211.0,Larry Peerce,Hollis Hodges,Treat Williams,United States,NaN,1175855.0,Metro-Goldwyn-Mayer (MGM),105.0
90,First Family,R,Comedy,1980,"December 25, 1980 (United States)",4.3,593.0,Buck Henry,Buck Henry,Bob Newhart,United States,NaN,15198912.0,F.F. Associates,97.0
91,Mantis Fist Fighter,NaN,Action,1980,"July 9, 1982 (United States)",6.7,230.0,Wing-Cho Yip,Hsin-Yi Chang,Ka-Yan Leung,Hong Kong,NaN,NaN,East Asia Film Company,89.0

In [21]:
#df.reset_index(drop=True,inplace=True) do not create a copy ,,,in original df changes

In [29]:
df2["rank"]=df2["score"].rank()   #gives a rank based on score
df2

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,rank
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,91.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,29.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,92.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,83.5
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,78.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,The Gong Show Movie,R,Comedy,1980,"May 23, 1980 (United States)",4.3,740.0,Chuck Barris,Chuck Barris,Chuck Barris,United States,NaN,6621520.0,Chuck Barris Productions,89.0,3.5
88,Gilda Live,R,Comedy,1980,"March 28, 1980 (United States)",6.8,599.0,Mike Nichols,Anne Beatts,Gilda Radner,United States,NaN,2261507.0,Broadway Productions,96.0,62.5
89,Why Would I Lie?,PG,Comedy,1980,"August 8, 1980 (United States)",6.5,211.0,Larry Peerce,Hollis Hodges,Treat Williams,United States,NaN,1175855.0,Metro-Goldwyn-Mayer (MGM),105.0,49.5
90,First Family,R,Comedy,1980,"December 25, 1980 (United States)",4.3,593.0,Buck Henry,Buck Henry,Bob Newhart,United States,NaN,15198912.0,F.F. Associates,97.0,3.5
91,Mantis Fist Fighter,NaN,Action,1980,"July 9, 1982 (United States)",6.7,230.0,Wing-Cho Yip,Hsin-Yi Chang,Ka-Yan Leung,Hong Kong,NaN,NaN,East Asia Film Company,89.0,57.0

In [33]:
#if you want a rank according to whose score is greater then
df2["rank"]=df2["score"].rank(ascending=False,method="dense")
df2
#dense gives the integer rank

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,rank
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,2.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,25.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,1.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,7.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,The Gong Show Movie,R,Comedy,1980,"May 23, 1980 (United States)",4.3,740.0,Chuck Barris,Chuck Barris,Chuck Barris,United States,NaN,6621520.0,Chuck Barris Productions,89.0,35.0
88,Gilda Live,R,Comedy,1980,"March 28, 1980 (United States)",6.8,599.0,Mike Nichols,Anne Beatts,Gilda Radner,United States,NaN,2261507.0,Broadway Productions,96.0,15.0
89,Why Would I Lie?,PG,Comedy,1980,"August 8, 1980 (United States)",6.5,211.0,Larry Peerce,Hollis Hodges,Treat Williams,United States,NaN,1175855.0,Metro-Goldwyn-Mayer (MGM),105.0,18.0
90,First Family,R,Comedy,1980,"December 25, 1980 (United States)",4.3,593.0,Buck Henry,Buck Henry,Bob Newhart,United States,NaN,15198912.0,F.F. Associates,97.0,35.0
91,Mantis Fist Fighter,NaN,Action,1980,"July 9, 1982 (United States)",6.7,230.0,Wing-Cho Yip,Hsin-Yi Chang,Ka-Yan Leung,Hong Kong,NaN,NaN,East Asia Film Company,89.0,16.0

In [34]:
df2[["name","year","genre","rating","votes","writer","star","country","runtime","budget","gross","director"]]
#gives columns based based on names given first

,name,year,genre,rating,votes,writer,star,country,runtime,budget,gross,director
0,The Shining,1980,Drama,R,927000.0,Stephen King,Jack Nicholson,United Kingdom,146.0,19000000.0,46998772.0,Stanley Kubrick
1,The Blue Lagoon,1980,Adventure,R,65000.0,Henry De Vere Stacpoole,Brooke Shields,United States,104.0,4500000.0,58853106.0,Randal Kleiser
2,Star Wars: Episode V - The Empire Strikes Back,1980,Action,PG,1200000.0,Leigh Brackett,Mark Hamill,United States,124.0,18000000.0,538375067.0,Irvin Kershner
3,Airplane!,1980,Comedy,PG,221000.0,Jim Abrahams,Robert Hays,United States,88.0,3500000.0,83453539.0,Jim Abrahams
4,Caddyshack,1980,Comedy,R,108000.0,Brian Doyle-Murray,Chevy Chase,United States,98.0,6000000.0,39846344.0,Harold Ramis
...,...,...,...,...,...,...,...,...,...,...,...,...
87,The Gong Show Movie,1980,Comedy,R,740.0,Chuck Barris,Chuck Barris,United States,89.0,NaN,6621520.0,Chuck Barris
88,Gilda Live,1980,Comedy,R,599.0,Anne Beatts,Gilda Radner,United States,96.0,NaN,2261507.0,Mike Nichols
89,Why Would I Lie?,1980,Comedy,PG,211.0,Hollis Hodges,Treat Williams,United States,105.0,NaN,1175855.0,Larry Peerce
90,First Family,1980,Comedy,R,593.0,Buck Henry,Bob Newhart,United States,97.0,NaN,15198912.0,Buck Henry
91,Mantis Fist Fighter,1980,Action,NaN,230.0,Hsin-Yi Chang,Ka-Yan Leung,Hong Kong,89.0,NaN,NaN,Wing-Cho Yip

In [40]:
col=["writer"]+[col for col in df2.columns if col!="writer"]
df2=df2[col]
df2
#This code moves the "writer" column to the first position while keeping the other columns in their original order.

,writer,name,rating,genre,year,released,score,votes,director,star,country,budget,gross,company,runtime,rank
0,Stephen King,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,2.0
1,Henry De Vere Stacpoole,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,25.0
2,Leigh Brackett,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,1.0
3,Jim Abrahams,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,7.0
4,Brian Doyle-Murray,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Chuck Barris,The Gong Show Movie,R,Comedy,1980,"May 23, 1980 (United States)",4.3,740.0,Chuck Barris,Chuck Barris,United States,NaN,6621520.0,Chuck Barris Productions,89.0,35.0
88,Anne Beatts,Gilda Live,R,Comedy,1980,"March 28, 1980 (United States)",6.8,599.0,Mike Nichols,Gilda Radner,United States,NaN,2261507.0,Broadway Productions,96.0,15.0
89,Hollis Hodges,Why Would I Lie?,PG,Comedy,1980,"August 8, 1980 (United States)",6.5,211.0,Larry Peerce,Treat Williams,United States,NaN,1175855.0,Metro-Goldwyn-Mayer (MGM),105.0,18.0
90,Buck Henry,First Family,R,Comedy,1980,"December 25, 1980 (United States)",4.3,593.0,Buck Henry,Bob Newhart,United States,NaN,15198912.0,F.F. Associates,97.0,35.0
91,Hsin-Yi Chang,Mantis Fist Fighter,NaN,Action,1980,"July 9, 1982 (United States)",6.7,230.0,Wing-Cho Yip,Ka-Yan Leung,Hong Kong,NaN,NaN,East Asia Film Company,89.0,16.0