In [1]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [5]:
#melt

# df.melt(id_vars,value_vars,var_name,value_name)

# id_vars--> columns which should be as it is
# value_vars-->columns which need to be changed 
# var_names-->columns name of changed columns
# val_names-->var_name renames the "variable" column.

In [21]:
df_long=df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"], var_name="Subject", value_name="Score")
df_long

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [23]:
#pivot

df_long.pivot(index="Name", columns="Subject", values="Score")

# index="Name": The unique values in the "Name" column will become the rows in the new DataFrame.
# columns="Subject": The unique values in the "Subject" column will become the columns in the new DataFrame.
# values="Score": The values from the "Score" column will populate the table

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89