In [1]:
import pandas as pd

In [23]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "z", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})  
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    z      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [24]:
df.groupby("Department")["Salary"].mean()    #group pf department then take salary column

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [30]:
type(df.groupby("Department")["Salary"].mean() )

pandas.core.series.Series

In [25]:
df.groupby("Team")["Salary"].count()  #group of team in that number of salary

Team
A    2
B    1
C    2
D    2
z    1
Name: Salary, dtype: int64

In [26]:
df.groupby("Team")["Salary"].sum()

Team
A    175
B     78
C    180
D    155
z     85
Name: Salary, dtype: int64

In [27]:
df.groupby("Team")["Salary"].min()

Team
A    85
B    78
C    88
D    75
z    85
Name: Salary, dtype: int64

In [28]:
df.groupby("Team")["Salary"].max()

Team
A    90
B    78
C    92
D    80
z    85
Name: Salary, dtype: int64

In [29]:
df.groupby(["Department","Team"])["Salary"].mean()

Department  Team
HR          A       87.5
IT          B       78.0
            z       85.0
Marketing   C       90.0
Sales       D       77.5
Name: Salary, dtype: float64

In [37]:
df.groupby("Department")["Salary"].agg(["mean","min","max"])   #group of department in that mean,,min of sal

            mean  min  max
Department
HR          87.5   85   90
IT          81.5   78   85
Marketing   90.0   88   92
Sales       77.5   75   80

In [46]:
type(df.groupby("Department")["Salary"].aggregate(["mean","min","max"]))

pandas.core.frame.DataFrame

In [45]:
df.groupby("Department")["Salary"].agg(
    avg_sal="mean",
    max_sal="max")

            avg_sal  max_sal
Department
HR             87.5       90
IT             81.5       85
Marketing      90.0       92
Sales          77.5       80

In [56]:
df["Team_avg"]=df.groupby("Department")["Salary"].transform("mean") #create a new col avg_sal of department ,in that avg of 
df                                                                  #sal

  Department Team Gender  Salary  Age   JoinDate  Team_avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    z      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5

In [58]:
df.groupby("Department").filter(lambda x:x["Salary"].mean()>85)

  Department Team Gender  Salary  Age   JoinDate  Team_avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0