In [2]:
import pandas as pd

In [3]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [5]:
pd.merge(employees,departments,on="DeptID") #merge employye and department on deptid where ddeptid values are common
                                            #inneer join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [8]:
#left join
pd.merge(employees,departments,on="DeptID",how="left") #prints each and every rows of left (employee),and common rows from 
                                                        #right(departments)

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [10]:
#right join
pd.merge(employees,departments,on="DeptID",how="right") #prints each and every rows of right (department),and common rows 
                                                        #from left(employee)

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [11]:
#outer join
pd.merge(employees,departments,on="DeptID",how="outer")#eachand every values of both df

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [12]:
#concatenating

In [25]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"],"score":[90,82]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"],"age":[40,32]})

pd.concat([df1,df2])

      Name  score   age
0    Alice   90.0   NaN
1      Bob   82.0   NaN
0  Charlie    NaN  40.0
1    David    NaN  32.0

In [26]:
pd.concat([df1,df2],axis=1)  #columnwise adds new column name

    Name  score     Name  age
0  Alice     90  Charlie   40
1    Bob     82    David   32