In [10]:
import pandas as pd

In [11]:
df=pd.read_csv("data.csv")
df

      Name  Marks  School
0      Sai     56  smvitm
1     john     76      hj
2  johnson     78      kk
3      joe     59     klo
4     riya     56      hf
5   allice     87    dhhd
6      bob     84    bsdk

In [12]:
df=df[df["Marks"]>75]
df

      Name  Marks School
1     john     76     hj
2  johnson     78     kk
5   allice     87   dhhd
6      bob     84   bsdk

In [13]:
df.to_csv("updated_data.csv",index=False)

In [15]:
df=pd.read_json("norm.json")
df

   id   name                                  address
0   1  Alice   {'city': 'Delhi', 'zipcode': '110001'}
1   2    Bob  {'city': 'Mumbai', 'zipcode': '440001'}

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       2 non-null      int64
 1   name     2 non-null      object
 2   address  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes

In [18]:
data=[
{"id":1,"name":"Alice","address":{"city":"Delhi","zipcode":"110001"}},
{"id":2,"name":"Bob","address":{"city":"Mumbai","zipcode":"440001"}}
]

In [20]:
df=pd.json_normalize(data)
df

   id   name address.city address.zipcode
0   1  Alice        Delhi          110001
1   2    Bob       Mumbai          440001

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2 non-null      int64
 1   name             2 non-null      object
 2   address.city     2 non-null      object
 3   address.zipcode  2 non-null      object
dtypes: int64(1), object(3)
memory usage: 196.0+ bytes